### ISSUE TITLE
Duplicative checking of accomodate matrix in SMP processing?

### ISSUE THREAD

**Issue by ambah** [KAPSARC/KTAB#110]
I have noticed that in the SMP model, in [`SMPState::probEduChlg()`](https://github.com/KAPSARC/KTAB/blob/f1d387ff780bfd23518387469d98ea67f12d4c3c/examples/smp/libsrc/smpbcn.cpp#L732), there is a test of whether the `accomodate` matrix is the identity matrix using `KBase::iMatP()`. 

Why must this test be performed with every run of `SMPState::probEduChlg()`? If the `accomodate` matrix is fixed for a particular state, shouldn't this only need to be tested once per state?

If so, for efficiency perhaps you could run and store the result of this test as part of the `SMPState::setAccomodate()` methods, and reference this result in `SMPState::probEduChlg()`. This would avoid duplicative efforts in the many runs of `SMPState::probEduChlg()`.

**Comment by ambah** [comment]
Similarly, it looks as if another one of these checks is being performed in [`SMPState::newIdeals()`](https://github.com/KAPSARC/KTAB/blob/9f8dccd256aa038ebcb661ccdd168a84072f325c/examples/smp/libsrc/smp.cpp#L603). This too could draw from the same stored result, although it likely does not affect performance as much.

**Comment by ambah** [comment]
I just noticed that the commit [Delta Utility Challenge Quadmap (#136)](https://github.com/KAPSARC/KTAB/commit/b636d0772b9e88eb7fb040781ee6caed0d426ab7) to the testing branch has reverted some of the fixes implemented for this issue. Please take a look at the changes to [smp.cpp](https://github.com/KAPSARC/KTAB/commit/b636d0772b9e88eb7fb040781ee6caed0d426ab7#diff-e4cd2a6be7b63a3b123aa8476c2456d1) and [smpbcn.cpp](https://github.com/KAPSARC/KTAB/commit/b636d0772b9e88eb7fb040781ee6caed0d426ab7#diff-8a75dbfce4839d0823ab3258f799f1e5), which undo the fixes introduced in [Pmat2 (#111)](https://github.com/KAPSARC/KTAB/commit/144a685f5472fcdd35fae26ec9600de448238ffc). Was this done intentionally?

**Comment by ahowe42** [comment]
You are correct.  This was unintentional.  I'll re-introduce your fix.

**Comment by bwise-7365** [comment]
This should now be reimplemented in both 'testing' and 'master'
