### ISSUE TITLE
Increase and Decrease number of actors by adding  + and - buttons.

### ISSUE THREAD

**Issue by lsyaseen** [KAPSARC/KTAB#160]
We can only decrease the number of actors by right clicking on the row. It would be easier if we can do both using buttons.

![increaseanddecrease](https://cloud.githubusercontent.com/assets/14147663/21293743/0ace7ad4-c53e-11e6-9895-3650e763f853.png)

**Comment by ahowe42** [comment]
Issue resolved with PR 230, so closed.
