### ISSUE TITLE
Add the ability to save the grid panel output into a csv file

### ISSUE THREAD

**Issue by lsyaseen** [KAPSARC/KTAB#162]
Users suggested the possibility of saving the output in the grid panel as a csv for each turn or all turns.

![save_to_csv](https://cloud.githubusercontent.com/assets/14147663/21293815/e0fae9f2-c53f-11e6-93c9-a5349d3d22fb.png)

**Comment by ahowe42** [comment]
[This](https://trello.com/c/vBilgY4y) Trello card has been created as at least a first step in resolving this issue.  To it easy for users to get access to the by-turn position data shown in the interface to facilitate analysis of the bargaining process, functionality will be implemented to export to .csv files by-dimension and by-turn position daa + by-dimension effective power.

**Comment by ahowe42** [comment]
Closing this issue as a result of PR 221.
