### ISSUE TITLE
Add the ability to save pictures of generated graphs

### ISSUE THREAD

**Issue by lsyaseen** [KAPSARC/KTAB#164]
Users are unable to have the option to save the visualizations generated as images. they are only able to take screenshots.

An option to save as an image using several image file formats.
**Suggestion for file formats:** _TIF, JPEG, PNG and GIF_

**Comment by ahowe42** [comment]
I think we'd be ok with BMP (highest quality), PNG (best for internet), and EPS (production-quality for publications).

Andrew

**Comment by lsyaseen** [comment]
@ahowe42 makes sense, we can use these and add more if necessary based on user-feedback.

**Comment by ahowe42** [comment]
This feature is currently in testing, and intended for release soon.
