### ISSUE TITLE
Make old "What's New" accessible

### ISSUE THREAD

**Issue by bwise-7365** [KAPSARC/KTAB#274]
It seems that currently the "What's New" file covers only the most recent update. If I need the change in build instructions that were in a prior "What's New", there is no obvious way to get them.

If the "What's New" file just added to the front, then people could find old instructions, as well as scroll down the page to see how much progress has been made between versions.

**Comment by ahowe42** [comment]
Well, this "What's New" is the first one we've done to document progress explicitly.  Even if their had been previous non-cumulative versions, wouldn't they be accessible in the previous release tarballs?

Anyway, my intent with this "What's New" file it to make it a cumulative running history, with progress for later versions appended at the top each time.  It seems cleaner to me to keep this information in `whatsnew.md`, separate from `readme.md`, but if you think it's better to put it all in `readme.md`, I'm happy to do that instead.

**Comment by bwise-7365** [comment]
cumulative running history sounds ideal
