### ISSUE TITLE
KTAB_SMP won't compile with 6.3

### ISSUE THREAD

**Issue by bwise-7365** [KAPSARC/KTAB#312]
Two lines must be slightly changed to make KTAB_SMP compile with gcc version 6.3 (I built KTAB in LMDE-3).

In KTAB\examples\smp\SMPQ\linegraph.cpp:491-492, the 'abs' functions should be disambiguated 
by changing them to 'std::abs'

This change created no problem with either GCC 4.8 or Visual Studio 2015 when I tested it.

**Comment by bwise-7365** [comment]
Addressed by pull-request 316, "Ambiguous abs"

**Comment by lsyaseen** [comment]
Fixed with #316
