### ISSUE TITLE
CMAKE scripts generate false positive builds on travis

### ISSUE THREAD

**Issue by davidrpugh** [KAPSARC/KTAB#52]
CMAKE scripts check for various dependencies, such as `tinyxml2`, and then print error messages if dependencies cannot be found, however there does not seem to be a rule to stop the build process at any point.  This results in the build "passing" even though it has failed.  We need to implement a rule in the CMAKE scripts to stop the build process if dependencies cannot be found.

**Comment by lsyaseen** [comment]
I think this has been resolved?
