### ISSUE TITLE
License issue with csv-parser

### ISSUE THREAD

**Issue by davidrpugh** [KAPSARC/KTAB#68]
@KTAB Are we currently making use of the csv-parser module whose source code we are currently distributing with KTAB?  The source code is license under GPL3 which is more restrictive that the MIT License that we are using for KTAB. 

We either need to change the license to GPL3 (which would probably rule out commercial use of the software by requiring commercial software using KTAB to be open sourced), or find a new csv parser.

**Comment by lsyaseen** [comment]
i am assuming this has been resolved after adding the MIT-Licensed "Minimalistic CSV Streams 1.7.9" library
